* Copy and Paste by Abram Hindle / skruntskrunt
  - This performance is based on the information in my computer's
    clipboard.
  - In this peformance I will be using copy and paste texts as
    prompts to an instrument that interprets text.
  - I am exploring text and its information theoretic relationship with 
    sound, embeddings, and time.
  - The instrument is multifacetted.
    - It contains a word based n-gram model that measures the surprise
      of new text. This surprise is audible. Suprise is correlated
      with cross-entropy.
    - It contains a character based 3-gram model that prompts the
      playing of grains of sound from 8 gigabytes of sounds. Each set
      of characters such as "aaa" or "dem" maps to a cluster of
      sounds from these 8gb of sounds. These sounds are represented by
      an embedding generated from a neural network (VGGish or OpenL3)
      and then placed into a 3 dimensional space using the
      dimensionality reduction tool technique called u-map. The u-map
      results of the embedding are then clustered by dbscan.
  - The source texts are not mine and I do not approve or agree with
    their content.

* Sources
  - Demonology https://ia902807.us.archive.org/6/items/demonologyanddev40686gut/40686-h/40686-h.htm
  - Mystic https://archive.org/stream/mysticthesaurus00whitgoog/mysticthesaurus00whitgoog_djvu.txt
  - Geometry https://archive.org/details/theodosiisphaeri00theo/page/6/mode/2up
  - https://archive.org/details/poetminoresgr00wint/page/238/mode/2up
  - De Occulta Philopshia https://archive.org/details/DeOccultaPhilosophiaJungCollection1533/page/n179/mode/2up
  - Monas Hieroglyphica https://archive.org/details/monas-hieroglyphica/mode/2up
  - https://archive.org/details/francis-barrett-the-magus-volume-1/page/n49/mode/2up
    https://archive.org/details/francis-barrett-the-magus-volume-1/page/n79/mode/2up
  - Philosophy of Natural Magic
    https://archive.org/details/HeinrichCorneliusAgrippa-PhilosophyOfNaturalMagicAllIiiVolumes_224/page/n103/mode/2up
  - Rosicrucians
    https://archive.org/details/franz-hartmann-secret-symbols-of-the-rosicrucians/page/12/mode/2up    
  - Cabalistic Writings
    https://archive.org/details/aleister-crowley-liber-777-sepher-sephiroth-and-others-qabalistics-writings/page/96/mode/2up
  - Angels and stuff
    https://archive.org/details/ac_goetia/page/n41/mode/2up
  - Book of solomon?
    https://archive.org/details/ac_goetia/page/n63/mode/2up
  - A treatise of spirits
    https://archive.org/details/b30538105/page/122/mode/2up
  - Minutes of a witchcraft trial
    https://archive.org/details/acollectionrare00websgoog/page/n168/mode/2up
